// Production-ready placeholder testimonials
// Location: Delhi NCR and Ayodhya

export const TESTIMONIALS_SEED = [
  {
    client_name: "Amit Sharma",
    location: "Dwarka, New Delhi",
    rating: 5,
    title: "Professional Team & Transparent Process",
    content: "Building a home always feels stressful, but SBBT made the entire journey smooth. Every stage was explained clearly, material quality matched the commitment, and regular updates gave us complete confidence. Highly recommended for anyone planning construction.",
    project_type: "Residential Construction",
    project_status: "Completed",
    is_featured: true,
    sort_order: 1,
    image_url: "https://images.unsplash.com/photo-1507003703711-9b7b6d7e3b3b?w=100&h=100&fit=crop&auto=format",
  },
  {
    client_name: "Priya Verma",
    location: "Noida Sector 76",
    rating: 5,
    title: "Excellent Quality Construction",
    content: "From foundation to finishing, everything was handled professionally. The project team listened to our requirements and delivered exactly what was promised. We are very happy with the workmanship and overall experience.",
    project_type: "Residential Construction",
    project_status: "Completed",
    is_featured: true,
    sort_order: 7,
    image_url: "https://images.unsplash.com/photo-1494790108377-be9c397d9dd3?w=100&h=100&fit=crop&auto=format",
  },
  {
    client_name: "Rahul Gupta",
    location: "Raj Nagar Extension, Ghaziabad",
    rating: 5,
    title: "Value for Money",
    content: "We compared multiple construction companies before choosing SBBT. Their transparent quotation and quality materials convinced us. The final result exceeded our expectations and stayed within our planned budget.",
    project_type: "Residential Construction",
    project_status: "Completed",
    is_featured: true,
    sort_order: 3,
    image_url: "https://images.unsplash.com/photo-1500648767791-30b6b7f3e3b3?w=100&h=100&fit=crop&auto=format",
  },
  {
    client_name: "Neha Singh",
    location: "Indirapuram, Ghaziabad",
    rating: 5,
    title: "Stress-Free Home Construction",
    content: "The project manager kept us informed throughout the construction process. Every query was answered quickly, and quality checks were performed regularly. We truly appreciate their professionalism.",
    project_type: "Residential Construction",
    project_status: "Completed",
    is_featured: true,
    sort_order: 9,
    image_url: "https://images.unsplash.com/photo-1487412720502-e6f7a0ed96c2?w=100&h=100&fit=crop&auto=format",
  },
  {
    client_name: "Saurabh Mishra",
    location: "Greater Noida West",
    rating: 5,
    title: "Highly Recommended",
    content: "The construction quality is excellent and the finishing work is impressive. The team maintained timelines, communicated well, and made the entire experience comfortable for our family.",
    project_type: "Residential Construction",
    project_status: "Completed",
    is_featured: true,
    sort_order: 12,
    image_url: "https://images.unsplash.com/photo-1539571258160-89d0841aab8c?w=100&h=100&fit=crop&auto=format",
  },
  {
    client_name: "Anjali Kapoor",
    location: "Rohini, Delhi",
    rating: 5,
    title: "Trustworthy Construction Partner",
    content: "Finding a reliable builder is difficult, but SBBT delivered exactly as committed. Their attention to detail and transparent working style gave us confidence from day one.",
    project_type: "Residential Construction",
    project_status: "Completed",
    is_featured: true,
    sort_order: 8,
    image_url: "https://images.unsplash.com/photo-1472097734473-d7f8e6a6e6d1?w=100&h=100&fit=crop&auto=format",
  },
  {
    client_name: "Vikas Yadav",
    location: "Gurugram Sector 57",
    rating: 5,
    title: "Quality Beyond Expectations",
    content: "The engineers maintained excellent quality throughout the project. Every construction stage was properly supervised, and the final outcome reflects true professionalism.",
    project_type: "Residential Construction",
    project_status: "Completed",
    is_featured: true,
    sort_order: 2,
    image_url: "https://images.unsplash.com/photo-1506794778202-cad84cf05f37?w=100&h=100&fit=crop&auto=format",
  },
  {
    client_name: "Ritu Agarwal",
    location: "Mayur Vihar, Delhi",
    rating: 5,
    title: "Great Communication",
    content: "We received regular progress updates with photos and detailed explanations. The entire process felt transparent, and we always knew what was happening at the site.",
    project_type: "Residential Construction",
    project_status: "Completed",
    is_featured: true,
    sort_order: 11,
    image_url: "https://images.unsplash.com/photo-1438761681033-6461ff7a8b82?w=100&h=100&fit=crop&auto=format",
  },
  {
    client_name: "Deepak Tiwari",
    location: "Ayodhya",
    rating: 5,
    title: "Perfect Dream Home",
    content: "We wanted a modern house with practical planning, and SBBT delivered beautifully. Their design suggestions were valuable, and the quality of construction has impressed our entire family.",
    project_type: "Residential Construction",
    project_status: "Completed",
    is_featured: true,
    sort_order: 4,
    image_url: "https://images.unsplash.com/photo-1500648767791-30b6b7f3e3b3?w=100&h=100&fit=crop&auto=format",
  },
  {
    client_name: "Nidhi Saxena",
    location: "Janakpuri, New Delhi",
    rating: 5,
    title: "Professional Execution",
    content: "Everything from planning to handover was organized and systematic. The site team was polite, responsive, and focused on delivering quality work without unnecessary delays.",
    project_type: "Residential Construction",
    project_status: "Completed",
    is_featured: true,
    sort_order: 10,
    image_url: "https://images.unsplash.com/photo-1487412720502-e6f7a0ed96c2?w=100&h=100&fit=crop&auto=format",
  },
  {
    client_name: "Mohit Bansal",
    location: "Lajpat Nagar, New Delhi",
    rating: 5,
    title: "Reliable Team",
    content: "The team maintained complete transparency in material selection and construction stages. We appreciated their honesty, timely communication, and commitment to delivering quality.",
    project_type: "Residential Construction",
    project_status: "Completed",
    is_featured: true,
    sort_order: 5,
    image_url: "https://images.unsplash.com/photo-1539571258160-89d0841aab8c?w=100&h=100&fit=crop&auto=format",
  },
  {
    client_name: "Shweta Srivastava",
    location: "Ayodhya",
    rating: 5,
    title: "Worth Every Rupee",
    content: "Choosing SBBT was one of our best decisions. The house was built with excellent workmanship, premium finishing, and professional site management. We confidently recommend them to anyone planning home construction.",
    project_type: "Residential Construction",
    project_status: "Completed",
    is_featured: true,
    sort_order: 6,
    image_url: "https://images.unsplash.com/photo-1494790108377-be9c397d9dd3?w=100&h=100&fit=crop&auto=format",
  },
];